services:
  api:
    build: .
    container_name: product_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app  # Mapeia a raiz do projeto para o /app do container
    # O comando abaixo garante que o Uvicorn ache o main dentro da pasta app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: padaria_postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      # O Docker vai ler do seu arquivo .env local
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: padaria_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: